version: "2.2"

services:
    flask:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: scetts/tts-server
        cpus: 1
        restart: unless-stopped
        environment:
            - "TTS_GLOW_TTS=4254"
            - "TTS_MULTIBAND_MELGAN=667775"
        volumes:
            - "./data/src/flask:/content/src/flask"
            - "./data/models:/content/models"
        ports: 
            - "5000:5000"